### ISSUE TITLE
Update Bower dependency for Firebase

### ISSUE THREAD

**Issue by jwngr** [Polymer/firebase-element#19]
The [Firebase dependency in the bower.json file](https://github.com/Polymer/firebase-element/blob/96bf163ae535a9bb43586976c3d4b05ede333bdb/bower.json#L6) should be updated. It is bad practice to use `*` for the semver as this will break every time Firebase releases a new major version number with breaking changes to API methods. Since Firebase follows proper semver policies, a better approach would be to use `1.x.x.` currently, and then `2.x.x` once #18 is fixed.

**Comment by ssorallen** [comment]
Closing this as fixed because the Firebase dependency was set to `^2.2` in PR #23.
